version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing Prisma CLI only..."
      - npm install -g prisma

  build:
    commands:
      - echo "Running Prisma migration..."
      - echo "Database URL is set"
      - cd backend
      - export DATABASE_URL=$AWS_RDS_DATABASE_URL
      - npx prisma migrate deploy
      - echo "Migration completed successfully!"

artifacts:
  files: []
