version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing Prisma CLI only..."
      - npm install -g prisma

  build:
    commands:
      - echo "Running Prisma migration..."
      - echo "Database URL is set"
      - npx prisma migrate deploy --schema=./aws/schema.prisma
      - echo "Migration completed successfully!"

artifacts:
  files: []
