name: Render Deploy

on:
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"
    types: [closed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリチェック
        uses: actions/checkout@v4

      - name: ファイル状況確認
        run: ls -la

      - name: インストール
        working-directory: backend
        run: npm install --production=false

      - name: ビルド
        working-directory: backend
        run: npm run build

      - name: Render.com にデプロイ
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true
