name: Render Deploy

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inspect files before checkout
        run: ls -la

      - name: Install dependencies
        working-directory: backend
        run: npm install

      - name: Build the project
        working-directory: backend
        run: npm run build

      - name: Deploy to project
        uses: ttskch/render-deploy@v1.0.0
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true
